services:
    php:
        build:
            context: ./php-env
            dockerfile: Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION}
        container_name: php-app-${PROJECT_NAME}
        volumes:
            # This is a bind mount
            # Syncs files between host and container
            # Allows editing code locally, you can use your editor (vim) on your host machine
            #   PHP inside the container will always see the latest version
            # Keeps container stateless.  You can rebuild or replace the container without losing code.
            - ${PROJECT_ROOT}:/var/www/html
        networks:
            # Attach container to the app-network network
            # Only containers on the app-network can see each other by default
            # Helps avoid conflicts if you run multiple projects locally
            - app-network
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "php", "-v"]
            interval: 10s
            timeout: 3s
            retries: 3
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

    nginx:
        image: nginx:stable
        container_name: nginx-${PROJECT_NAME}
        ports:
            - "${PROJECT_PHP_PORT}:80"
        volumes:
            - ${PROJECT_ROOT}:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network

    db:
        image: mysql:8
        container_name: mysql-db-${PROJECT_NAME}
        ports:
            - "${PROJECT_DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
            interval: 5s
            timeout: 3s
            retries: 3

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin-ui-${PROJECT_NAME}
        ports:
            # Maps localhost:8080 on your computer to port 80 inside phpMyAdmin container
            # Port 80 on your host may already be used by another web server (Apache/Nginx)
            - "${PROJECT_PMA_PORT}:80"
        environment:
            PMA_HOST: db
        depends_on:
            db:
                condition: service_healthy
        networks:
            - app-network

volumes:
    mysql-data:

networks:
    # Defines the network for Docker compose
    app-network:
